import { Sticker } from './types';

export const STICKER_CATEGORIES = [
  { id: 'recent', label: 'Recent', icon: 'time-outline' },
  { id: 'fav', label: 'Loved', icon: 'heart-outline' },
  { id: 'orbit', label: 'Orbit', icon: 'planet-outline' },
  { id: 'mood', label: 'Mood', icon: 'happy-outline' },
  { id: 'campus', label: 'Campus', icon: 'school-outline' },
  { id: 'signal', label: 'Signals', icon: 'radio-outline' },
] as const;

export const STICKERS: Sticker[] = [
  { id: 'o1', emoji: '🪐', label: 'Planet', category: 'orbit' },
  { id: 'o2', emoji: '🌌', label: 'Galaxy', category: 'orbit' },
  { id: 'o3', emoji: '🚀', label: 'Launch', category: 'orbit' },
  { id: 'o4', emoji: '☄️', label: 'Comet', category: 'orbit' },
  { id: 'o5', emoji: '🌟', label: 'Star', category: 'orbit', animated: true },
  { id: 'o6', emoji: '💫', label: 'Dizzy', category: 'orbit', animated: true },
  { id: 'o7', emoji: '🛸', label: 'UFO', category: 'orbit' },
  { id: 'o8', emoji: '🌙', label: 'Moon', category: 'orbit' },
  { id: 'o9', emoji: '🛰️', label: 'Sat', category: 'orbit' },
  { id: 'o10', emoji: '✨', label: 'Spark', category: 'orbit', animated: true },
  { id: 'o11', emoji: '🌍', label: 'Earth', category: 'orbit' },
  { id: 'o12', emoji: '🔭', label: 'Scope', category: 'orbit' },
  { id: 'm1', emoji: '😂', label: 'Lol', category: 'mood', animated: true },
  { id: 'm2', emoji: '😍', label: 'Love', category: 'mood' },
  { id: 'm3', emoji: '😎', label: 'Cool', category: 'mood' },
  { id: 'm4', emoji: '🤯', label: 'Mind', category: 'mood' },
  { id: 'm5', emoji: '😴', label: 'Sleep', category: 'mood' },
  { id: 'm6', emoji: '🥲', label: 'Tear', category: 'mood' },
  { id: 'm7', emoji: '🫡', label: 'Salute', category: 'mood' },
  { id: 'm8', emoji: '😤', label: 'Hype', category: 'mood' },
  { id: 'm9', emoji: '🤗', label: 'Hug', category: 'mood' },
  { id: 'm10', emoji: '🫠', label: 'Melt', category: 'mood' },
  { id: 'm11', emoji: '🥺', label: 'Please', category: 'mood' },
  { id: 'm12', emoji: '😈', label: 'Mischief', category: 'mood' },
  { id: 'c1', emoji: '🎓', label: 'Grad', category: 'campus' },
  { id: 'c2', emoji: '📚', label: 'Books', category: 'campus' },
  { id: 'c3', emoji: '🧠', label: 'Brain', category: 'campus' },
  { id: 'c4', emoji: '☕', label: 'Fuel', category: 'campus' },
  { id: 'c5', emoji: '🎧', label: 'Focus', category: 'campus' },
  { id: 'c6', emoji: '📝', label: 'Notes', category: 'campus' },
  { id: 'c7', emoji: '🏆', label: 'Win', category: 'campus' },
  { id: 'c8', emoji: '🔥', label: 'Fire', category: 'campus', animated: true },
  { id: 'c9', emoji: '💡', label: 'Idea', category: 'campus' },
  { id: 'c10', emoji: '🧪', label: 'Lab', category: 'campus' },
  { id: 'c11', emoji: '🕹️', label: 'Play', category: 'campus' },
  { id: 'c12', emoji: '🖤', label: 'House', category: 'campus' },
  { id: 's1', emoji: '✅', label: 'Yes', category: 'signal' },
  { id: 's2', emoji: '❌', label: 'No', category: 'signal' },
  { id: 's3', emoji: '👀', label: 'Seen', category: 'signal' },
  { id: 's4', emoji: '💬', label: 'Talk', category: 'signal' },
  { id: 's5', emoji: '📣', label: 'Call', category: 'signal' },
  { id: 's6', emoji: '🤝', label: 'Deal', category: 'signal' },
  { id: 's7', emoji: '🙌', label: 'Up', category: 'signal' },
  { id: 's8', emoji: '🫶', label: 'Care', category: 'signal' },
  { id: 's9', emoji: '⚡', label: 'Zap', category: 'signal', animated: true },
  { id: 's10', emoji: '🎯', label: 'Hit', category: 'signal' },
  { id: 's11', emoji: '🍀', label: 'Luck', category: 'signal' },
  { id: 's12', emoji: '💌', label: 'Note', category: 'signal' },
];

export function stickerById(id: string) {
  return STICKERS.find((s) => s.id === id);
}
